import type { ClassScheduleEntry, DayIndex } from '@/types'

// ─── Time slots (Philippine semester blocks) ──────────────────────────────────
// Earliest: 07:45  |  Latest end: 20:30 (8:30 PM)
// Blocks: 1h30m each
export const TIME_SLOTS = [
  { start: '07:45', end: '09:15' },
  { start: '09:15', end: '10:45' },
  { start: '10:45', end: '12:15' },
  { start: '12:15', end: '13:45' },
  { start: '13:45', end: '15:15' },
  { start: '15:15', end: '16:45' },
  { start: '16:45', end: '18:15' },
  { start: '18:15', end: '19:45' },
  { start: '19:00', end: '20:30' },
] as const

// ─── Faculty roster ───────────────────────────────────────────────────────────
export const FACULTY: Array<{ id: string; name: string }> = [
  { id: 'f01', name: 'Prof. Maria Santos'     },
  { id: 'f02', name: 'Prof. Juan Dela Cruz'   },
  { id: 'f03', name: 'Prof. Ana Reyes'        },
  { id: 'f04', name: 'Prof. Carlos Mendoza'   },
  { id: 'f05', name: 'Prof. Luz Cruz'         },
  { id: 'f06', name: 'Prof. Ben Torres'       },
  { id: 'f07', name: 'Prof. Ricardo Lim'      },
  { id: 'f08', name: 'Prof. Joana Ocampo'     },
  { id: 'f09', name: 'Prof. Dennis Aquino'    },
  { id: 'f10', name: 'Prof. Grace Villanueva' },
  { id: 'f11', name: 'Prof. Mark Evangelista' },
  { id: 'f12', name: 'Prof. Nilda Soriano'    },
]

// ─── Course pool ─────────────────────────────────────────────────────────────
const COURSES: Array<{ code: string; subject: string }> = [
  { code: 'COMP 101', subject: 'Introduction to Computing'       },
  { code: 'PROG 111', subject: 'Computer Programming 1'          },
  { code: 'PROG 112', subject: 'Computer Programming 2'          },
  { code: 'DSALG 21', subject: 'Data Structures & Algorithms'    },
  { code: 'DBMS 301', subject: 'Database Management Systems'     },
  { code: 'WEBDEV 2', subject: 'Web Development'                 },
  { code: 'NETAD 11', subject: 'Network Administration'          },
  { code: 'OS 201',   subject: 'Operating Systems'               },
  { code: 'SOFTENG 3',subject: 'Software Engineering'            },
  { code: 'MOBDEV 4', subject: 'Mobile Application Development'  },
  { code: 'COMPORG 2',subject: 'Computer Organization'           },
  { code: 'INFOSEC 4',subject: 'Information Assurance & Security'},
  { code: 'SA&D 301', subject: 'Systems Analysis & Design'       },
  { code: 'COMPG 41', subject: 'Computer Graphics'               },
  { code: 'AIML 411', subject: 'Artificial Intelligence & ML'    },
]

// ─── Section codes ────────────────────────────────────────────────────────────
const SECTIONS = [
  'BSCS-1A','BSCS-1B','BSCS-2A','BSCS-2B','BSCS-3A','BSCS-3B',
  'BSIT-1A','BSIT-1B','BSIT-2A','BSIT-2B','BSIT-3A','BSIT-3B',
  'BSCS-4A','BSCS-4B','BSIT-4A','BSIT-4B',
]

// ─── Deterministic schedule builder ──────────────────────────────────────────
// Each lab × day → fill slots with courses, leaving some gaps (no class)
type Slot = { slot: number; courseIdx: number; facultyIdx: number; sectionIdx: number }

const LAB_SLOTS: Record<string, Slot[][]> = {
  // [labId]: array[6 days] of occupied slots
  cl1: [
    // Mon
    [{ slot:0, courseIdx:0, facultyIdx:0, sectionIdx:0  },
     { slot:1, courseIdx:1, facultyIdx:1, sectionIdx:1  },
     { slot:2, courseIdx:2, facultyIdx:2, sectionIdx:2  },
     { slot:4, courseIdx:3, facultyIdx:3, sectionIdx:3  },
     { slot:5, courseIdx:4, facultyIdx:4, sectionIdx:4  },
     { slot:7, courseIdx:5, facultyIdx:0, sectionIdx:5  }],
    // Tue
    [{ slot:0, courseIdx:6, facultyIdx:5, sectionIdx:6  },
     { slot:2, courseIdx:7, facultyIdx:6, sectionIdx:7  },
     { slot:3, courseIdx:8, facultyIdx:7, sectionIdx:8  },
     { slot:5, courseIdx:9, facultyIdx:8, sectionIdx:9  },
     { slot:8, courseIdx:10,facultyIdx:9, sectionIdx:10 }],
    // Wed
    [{ slot:0, courseIdx:1, facultyIdx:1, sectionIdx:0  },
     { slot:1, courseIdx:2, facultyIdx:2, sectionIdx:1  },
     { slot:3, courseIdx:11,facultyIdx:10,sectionIdx:2  },
     { slot:5, courseIdx:12,facultyIdx:11,sectionIdx:3  },
     { slot:7, courseIdx:13,facultyIdx:0, sectionIdx:4  }],
    // Thu
    [{ slot:1, courseIdx:14,facultyIdx:1, sectionIdx:5  },
     { slot:2, courseIdx:0, facultyIdx:2, sectionIdx:6  },
     { slot:4, courseIdx:3, facultyIdx:3, sectionIdx:7  },
     { slot:6, courseIdx:5, facultyIdx:4, sectionIdx:8  },
     { slot:8, courseIdx:6, facultyIdx:5, sectionIdx:9  }],
    // Fri
    [{ slot:0, courseIdx:7, facultyIdx:6, sectionIdx:10 },
     { slot:2, courseIdx:8, facultyIdx:7, sectionIdx:11 },
     { slot:4, courseIdx:9, facultyIdx:8, sectionIdx:12 },
     { slot:6, courseIdx:10,facultyIdx:9, sectionIdx:13 }],
    // Sat
    [{ slot:0, courseIdx:4, facultyIdx:4, sectionIdx:14 },
     { slot:1, courseIdx:11,facultyIdx:10,sectionIdx:15 },
     { slot:2, courseIdx:12,facultyIdx:11,sectionIdx:0  },
     { slot:4, courseIdx:13,facultyIdx:0, sectionIdx:1  }],
  ],
  cl2: [
    [{ slot:0, courseIdx:2, facultyIdx:1, sectionIdx:2  },
     { slot:1, courseIdx:3, facultyIdx:2, sectionIdx:3  },
     { slot:3, courseIdx:5, facultyIdx:3, sectionIdx:4  },
     { slot:5, courseIdx:7, facultyIdx:4, sectionIdx:5  },
     { slot:8, courseIdx:9, facultyIdx:5, sectionIdx:6  }],
    [{ slot:1, courseIdx:10,facultyIdx:6, sectionIdx:7  },
     { slot:2, courseIdx:11,facultyIdx:7, sectionIdx:8  },
     { slot:4, courseIdx:12,facultyIdx:8, sectionIdx:9  },
     { slot:6, courseIdx:0, facultyIdx:9, sectionIdx:10 }],
    [{ slot:0, courseIdx:1, facultyIdx:10,sectionIdx:11 },
     { slot:2, courseIdx:4, facultyIdx:11,sectionIdx:12 },
     { slot:4, courseIdx:6, facultyIdx:0, sectionIdx:13 },
     { slot:7, courseIdx:8, facultyIdx:1, sectionIdx:14 }],
    [{ slot:1, courseIdx:13,facultyIdx:2, sectionIdx:15 },
     { slot:3, courseIdx:14,facultyIdx:3, sectionIdx:0  },
     { slot:5, courseIdx:2, facultyIdx:4, sectionIdx:1  },
     { slot:7, courseIdx:3, facultyIdx:5, sectionIdx:2  }],
    [{ slot:0, courseIdx:5, facultyIdx:6, sectionIdx:3  },
     { slot:2, courseIdx:7, facultyIdx:7, sectionIdx:4  },
     { slot:4, courseIdx:9, facultyIdx:8, sectionIdx:5  },
     { slot:6, courseIdx:11,facultyIdx:9, sectionIdx:6  }],
    [{ slot:0, courseIdx:12,facultyIdx:10,sectionIdx:7  },
     { slot:1, courseIdx:4, facultyIdx:11,sectionIdx:8  },
     { slot:3, courseIdx:6, facultyIdx:0, sectionIdx:9  }],
  ],
  cl3: [
    [{ slot:0, courseIdx:4, facultyIdx:2, sectionIdx:4  },
     { slot:2, courseIdx:6, facultyIdx:3, sectionIdx:5  },
     { slot:4, courseIdx:8, facultyIdx:4, sectionIdx:6  },
     { slot:6, courseIdx:10,facultyIdx:5, sectionIdx:7  }],
    [{ slot:1, courseIdx:0, facultyIdx:6, sectionIdx:8  },
     { slot:3, courseIdx:2, facultyIdx:7, sectionIdx:9  },
     { slot:5, courseIdx:4, facultyIdx:8, sectionIdx:10 },
     { slot:7, courseIdx:6, facultyIdx:9, sectionIdx:11 }],
    [{ slot:0, courseIdx:8, facultyIdx:10,sectionIdx:12 },
     { slot:2, courseIdx:10,facultyIdx:11,sectionIdx:13 },
     { slot:4, courseIdx:12,facultyIdx:0, sectionIdx:14 },
     { slot:6, courseIdx:14,facultyIdx:1, sectionIdx:15 }],
    [{ slot:0, courseIdx:1, facultyIdx:2, sectionIdx:0  },
     { slot:2, courseIdx:3, facultyIdx:3, sectionIdx:1  },
     { slot:5, courseIdx:5, facultyIdx:4, sectionIdx:2  },
     { slot:8, courseIdx:7, facultyIdx:5, sectionIdx:3  }],
    [{ slot:1, courseIdx:9, facultyIdx:6, sectionIdx:4  },
     { slot:3, courseIdx:11,facultyIdx:7, sectionIdx:5  },
     { slot:5, courseIdx:13,facultyIdx:8, sectionIdx:6  }],
    [{ slot:0, courseIdx:0, facultyIdx:9, sectionIdx:7  },
     { slot:1, courseIdx:2, facultyIdx:10,sectionIdx:8  },
     { slot:2, courseIdx:4, facultyIdx:11,sectionIdx:9  }],
  ],
  cl4: [
    [{ slot:1, courseIdx:5, facultyIdx:3, sectionIdx:10 },
     { slot:3, courseIdx:8, facultyIdx:4, sectionIdx:11 },
     { slot:5, courseIdx:11,facultyIdx:5, sectionIdx:12 },
     { slot:7, courseIdx:14,facultyIdx:6, sectionIdx:13 }],
    [{ slot:0, courseIdx:2, facultyIdx:7, sectionIdx:14 },
     { slot:2, courseIdx:5, facultyIdx:8, sectionIdx:15 },
     { slot:4, courseIdx:8, facultyIdx:9, sectionIdx:0  },
     { slot:6, courseIdx:11,facultyIdx:10,sectionIdx:1  }],
    [{ slot:1, courseIdx:0, facultyIdx:11,sectionIdx:2  },
     { slot:3, courseIdx:3, facultyIdx:0, sectionIdx:3  },
     { slot:5, courseIdx:6, facultyIdx:1, sectionIdx:4  },
     { slot:7, courseIdx:9, facultyIdx:2, sectionIdx:5  }],
    [{ slot:0, courseIdx:12,facultyIdx:3, sectionIdx:6  },
     { slot:2, courseIdx:13,facultyIdx:4, sectionIdx:7  },
     { slot:4, courseIdx:0, facultyIdx:5, sectionIdx:8  }],
    [{ slot:1, courseIdx:4, facultyIdx:6, sectionIdx:9  },
     { slot:3, courseIdx:7, facultyIdx:7, sectionIdx:10 },
     { slot:6, courseIdx:10,facultyIdx:8, sectionIdx:11 }],
    [{ slot:0, courseIdx:1, facultyIdx:9, sectionIdx:12 },
     { slot:2, courseIdx:6, facultyIdx:10,sectionIdx:13 }],
  ],
  cl5: [
    [{ slot:2, courseIdx:3, facultyIdx:4, sectionIdx:14 },
     { slot:4, courseIdx:6, facultyIdx:5, sectionIdx:15 },
     { slot:6, courseIdx:9, facultyIdx:6, sectionIdx:0  }],
    [{ slot:0, courseIdx:1, facultyIdx:7, sectionIdx:1  },
     { slot:3, courseIdx:4, facultyIdx:8, sectionIdx:2  },
     { slot:5, courseIdx:7, facultyIdx:9, sectionIdx:3  },
     { slot:8, courseIdx:10,facultyIdx:10,sectionIdx:4  }],
    [{ slot:1, courseIdx:2, facultyIdx:11,sectionIdx:5  },
     { slot:3, courseIdx:5, facultyIdx:0, sectionIdx:6  },
     { slot:5, courseIdx:8, facultyIdx:1, sectionIdx:7  }],
    [{ slot:0, courseIdx:11,facultyIdx:2, sectionIdx:8  },
     { slot:2, courseIdx:13,facultyIdx:3, sectionIdx:9  },
     { slot:4, courseIdx:0, facultyIdx:4, sectionIdx:10 }],
    [{ slot:1, courseIdx:12,facultyIdx:5, sectionIdx:11 },
     { slot:3, courseIdx:14,facultyIdx:6, sectionIdx:12 },
     { slot:6, courseIdx:3, facultyIdx:7, sectionIdx:13 }],
    [{ slot:0, courseIdx:5, facultyIdx:8, sectionIdx:14 },
     { slot:1, courseIdx:7, facultyIdx:9, sectionIdx:15 }],
  ],
  nl1: [
    [{ slot:1, courseIdx:6, facultyIdx:0, sectionIdx:0  },
     { slot:3, courseIdx:8, facultyIdx:1, sectionIdx:1  },
     { slot:5, courseIdx:10,facultyIdx:2, sectionIdx:2  }],
    [{ slot:0, courseIdx:1, facultyIdx:3, sectionIdx:3  },
     { slot:2, courseIdx:3, facultyIdx:4, sectionIdx:4  },
     { slot:4, courseIdx:5, facultyIdx:5, sectionIdx:5  },
     { slot:7, courseIdx:7, facultyIdx:6, sectionIdx:6  }],
    [{ slot:1, courseIdx:9, facultyIdx:7, sectionIdx:7  },
     { slot:3, courseIdx:11,facultyIdx:8, sectionIdx:8  },
     { slot:5, courseIdx:13,facultyIdx:9, sectionIdx:9  }],
    [{ slot:0, courseIdx:0, facultyIdx:10,sectionIdx:10 },
     { slot:2, courseIdx:2, facultyIdx:11,sectionIdx:11 },
     { slot:4, courseIdx:4, facultyIdx:0, sectionIdx:12 }],
    [{ slot:1, courseIdx:12,facultyIdx:1, sectionIdx:13 },
     { slot:3, courseIdx:14,facultyIdx:2, sectionIdx:14 }],
    [{ slot:0, courseIdx:6, facultyIdx:3, sectionIdx:15 },
     { slot:2, courseIdx:8, facultyIdx:4, sectionIdx:0  }],
  ],
  sl1: [
    [{ slot:0, courseIdx:14,facultyIdx:5, sectionIdx:1  },
     { slot:2, courseIdx:11,facultyIdx:6, sectionIdx:2  },
     { slot:4, courseIdx:7, facultyIdx:7, sectionIdx:3  },
     { slot:6, courseIdx:3, facultyIdx:8, sectionIdx:4  }],
    [{ slot:1, courseIdx:13,facultyIdx:9, sectionIdx:5  },
     { slot:3, courseIdx:9, facultyIdx:10,sectionIdx:6  },
     { slot:5, courseIdx:5, facultyIdx:11,sectionIdx:7  }],
    [{ slot:0, courseIdx:1, facultyIdx:0, sectionIdx:8  },
     { slot:2, courseIdx:3, facultyIdx:1, sectionIdx:9  },
     { slot:4, courseIdx:5, facultyIdx:2, sectionIdx:10 },
     { slot:8, courseIdx:7, facultyIdx:3, sectionIdx:11 }],
    [{ slot:1, courseIdx:9, facultyIdx:4, sectionIdx:12 },
     { slot:3, courseIdx:11,facultyIdx:5, sectionIdx:13 },
     { slot:7, courseIdx:13,facultyIdx:6, sectionIdx:14 }],
    [{ slot:0, courseIdx:0, facultyIdx:7, sectionIdx:15 },
     { slot:2, courseIdx:4, facultyIdx:8, sectionIdx:0  },
     { slot:5, courseIdx:8, facultyIdx:9, sectionIdx:1  }],
    [{ slot:1, courseIdx:2, facultyIdx:10,sectionIdx:2  },
     { slot:3, courseIdx:6, facultyIdx:11,sectionIdx:3  }],
  ],
  sl2: [
    [{ slot:0, courseIdx:10,facultyIdx:1, sectionIdx:4  },
     { slot:2, courseIdx:12,facultyIdx:2, sectionIdx:5  },
     { slot:5, courseIdx:0, facultyIdx:3, sectionIdx:6  },
     { slot:7, courseIdx:2, facultyIdx:4, sectionIdx:7  }],
    [{ slot:1, courseIdx:4, facultyIdx:5, sectionIdx:8  },
     { slot:3, courseIdx:6, facultyIdx:6, sectionIdx:9  },
     { slot:5, courseIdx:8, facultyIdx:7, sectionIdx:10 }],
    [{ slot:0, courseIdx:10,facultyIdx:8, sectionIdx:11 },
     { slot:2, courseIdx:12,facultyIdx:9, sectionIdx:12 },
     { slot:4, courseIdx:14,facultyIdx:10,sectionIdx:13 }],
    [{ slot:1, courseIdx:1, facultyIdx:11,sectionIdx:14 },
     { slot:3, courseIdx:3, facultyIdx:0, sectionIdx:15 },
     { slot:6, courseIdx:5, facultyIdx:1, sectionIdx:0  }],
    [{ slot:0, courseIdx:7, facultyIdx:2, sectionIdx:1  },
     { slot:2, courseIdx:9, facultyIdx:3, sectionIdx:2  },
     { slot:4, courseIdx:11,facultyIdx:4, sectionIdx:3  }],
    [{ slot:1, courseIdx:13,facultyIdx:5, sectionIdx:4  },
     { slot:2, courseIdx:0, facultyIdx:6, sectionIdx:5  }],
  ],
  emc: [
    [{ slot:0, courseIdx:2, facultyIdx:7, sectionIdx:6  },
     { slot:2, courseIdx:4, facultyIdx:8, sectionIdx:7  },
     { slot:4, courseIdx:6, facultyIdx:9, sectionIdx:8  },
     { slot:6, courseIdx:8, facultyIdx:10,sectionIdx:9  }],
    [{ slot:1, courseIdx:10,facultyIdx:11,sectionIdx:10 },
     { slot:3, courseIdx:12,facultyIdx:0, sectionIdx:11 },
     { slot:5, courseIdx:14,facultyIdx:1, sectionIdx:12 }],
    [{ slot:0, courseIdx:1, facultyIdx:2, sectionIdx:13 },
     { slot:2, courseIdx:3, facultyIdx:3, sectionIdx:14 },
     { slot:4, courseIdx:5, facultyIdx:4, sectionIdx:15 },
     { slot:7, courseIdx:7, facultyIdx:5, sectionIdx:0  }],
    [{ slot:1, courseIdx:9, facultyIdx:6, sectionIdx:1  },
     { slot:3, courseIdx:11,facultyIdx:7, sectionIdx:2  },
     { slot:6, courseIdx:13,facultyIdx:8, sectionIdx:3  }],
    [{ slot:0, courseIdx:0, facultyIdx:9, sectionIdx:4  },
     { slot:2, courseIdx:2, facultyIdx:10,sectionIdx:5  },
     { slot:4, courseIdx:4, facultyIdx:11,sectionIdx:6  }],
    [{ slot:1, courseIdx:6, facultyIdx:0, sectionIdx:7  },
     { slot:3, courseIdx:8, facultyIdx:1, sectionIdx:8  }],
  ],
}

// ─── Build flat schedule array ────────────────────────────────────────────────
let _seq = 1

export const CLASS_SCHEDULE: ClassScheduleEntry[] = Object.entries(LAB_SLOTS).flatMap(
  ([labId, days]) =>
    days.flatMap((daySlots, dayIdx) =>
      daySlots.map(({ slot, courseIdx, facultyIdx, sectionIdx }) => {
        const c = COURSES[courseIdx % COURSES.length]
        const f = FACULTY[facultyIdx % FACULTY.length]
        const t = TIME_SLOTS[slot]
        return {
          id:             `cs-${labId}-d${dayIdx}-s${slot}-${_seq++}`,
          labId,
          day:            dayIdx as DayIndex,
          startTime:      t.start,
          endTime:        t.end,
          courseCode:     c.code,
          subject:        c.subject,
          section:        SECTIONS[sectionIdx % SECTIONS.length],
          instructorId:   f.id,
          instructorName: f.name,
        } satisfies ClassScheduleEntry
      })
    )
)
